// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgnhgjdoxuqrcxygtgdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnbmhnamRveHVxcmN4eWd0Z2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTIwNTgsImV4cCI6MjA1ODM4ODA1OH0.4lo71CNOoL7IRevh-mxiOq-Lp5svUa5bNx9C4DZ7G1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);